version: '3'
services:
  app:
    container_name: mean-user-auth
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - db
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'